### PR TITLE
Fix issue/pr comments width

### PR DESCRIPTION
**Pull request by s0undt3ch**
Before:

before

After:

after

### CODE REVIEW

**Comment by cfoellmann** [comment]
this happens when you have these big images in the issue, right?
Your fix doesn't keep `.discussion-sidebar` at its absolute/fixed width!

Please send the PR to https://github.com/mdo/github-wide !!

**Comment by cfoellmann** [comment]
One more thing:
question
I suspect that is a Greasemonkey(-like) script. What does it do?

**Comment by s0undt3ch** [comment]
This happens every time, with or without images.

For the second question, its zenhub, Google it up :)

**Comment by cfoellmann** [comment]
Doesn't happen in my browser (FF current/Win10):
This issue page:
screenshot 2015-08-05 14 03 42
I removed the images with Firebug:
screenshot 2015-08-05 14 04 09

**Comment by cfoellmann** [comment]
by posting my last reply I see that it overflows everything with these big images.
We should move this to https://github.com/mdo/github-wide/issues

**Pull request closed without merging**
